window.esdocSearchIndex = [
  [
    "ovchip-api~ovapi",
    "class/src/index.js~OVApi.html",
    "<span>OVApi</span> <span class=\"search-result-import-path\">ovchip-api</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index.js~ovapi#_accesstoken",
    "class/src/index.js~OVApi.html#instance-member-_accessToken",
    "src/index.js~OVApi#_accessToken",
    "member"
  ],
  [
    "src/index.js~ovapi#_actionendpoint",
    "class/src/index.js~OVApi.html#instance-member-_actionEndpoint",
    "src/index.js~OVApi#_actionEndpoint",
    "member"
  ],
  [
    "src/index.js~ovapi#_cards",
    "class/src/index.js~OVApi.html#instance-member-_cards",
    "src/index.js~OVApi#_cards",
    "member"
  ],
  [
    "src/index.js~ovapi#_clientid",
    "class/src/index.js~OVApi.html#instance-member-_clientId",
    "src/index.js~OVApi#_clientId",
    "member"
  ],
  [
    "src/index.js~ovapi#_clientsecret",
    "class/src/index.js~OVApi.html#instance-member-_clientSecret",
    "src/index.js~OVApi#_clientSecret",
    "member"
  ],
  [
    "src/index.js~ovapi#_datatoken",
    "class/src/index.js~OVApi.html#instance-member-_dataToken",
    "src/index.js~OVApi#_dataToken",
    "member"
  ],
  [
    "src/index.js~ovapi#_expiredate",
    "class/src/index.js~OVApi.html#instance-member-_expireDate",
    "src/index.js~OVApi#_expireDate",
    "member"
  ],
  [
    "src/index.js~ovapi#_login",
    "class/src/index.js~OVApi.html#instance-method-_login",
    "src/index.js~OVApi#_login",
    "method"
  ],
  [
    "src/index.js~ovapi#_loginendpoint",
    "class/src/index.js~OVApi.html#instance-member-_loginEndpoint",
    "src/index.js~OVApi#_loginEndpoint",
    "member"
  ],
  [
    "src/index.js~ovapi#_logintoken",
    "class/src/index.js~OVApi.html#instance-member-_loginToken",
    "src/index.js~OVApi#_loginToken",
    "member"
  ],
  [
    "src/index.js~ovapi#_oauthrequest",
    "class/src/index.js~OVApi.html#instance-method-_oAuthRequest",
    "src/index.js~OVApi#_oAuthRequest",
    "method"
  ],
  [
    "src/index.js~ovapi#_password",
    "class/src/index.js~OVApi.html#instance-member-_password",
    "src/index.js~OVApi#_password",
    "member"
  ],
  [
    "src/index.js~ovapi#_refreshtoken",
    "class/src/index.js~OVApi.html#instance-member-_refreshToken",
    "src/index.js~OVApi#_refreshToken",
    "member"
  ],
  [
    "src/index.js~ovapi#_tlsrequest",
    "class/src/index.js~OVApi.html#instance-method-_tlsRequest",
    "src/index.js~OVApi#_tlsRequest",
    "method"
  ],
  [
    "src/index.js~ovapi#_username",
    "class/src/index.js~OVApi.html#instance-member-_username",
    "src/index.js~OVApi#_username",
    "member"
  ],
  [
    "src/index.js~ovapi#authorize",
    "class/src/index.js~OVApi.html#instance-method-authorize",
    "src/index.js~OVApi#authorize",
    "method"
  ],
  [
    "src/index.js~ovapi#constructor",
    "class/src/index.js~OVApi.html#instance-constructor-constructor",
    "src/index.js~OVApi#constructor",
    "method"
  ],
  [
    "src/index.js~ovapi#getcards",
    "class/src/index.js~OVApi.html#instance-method-getCards",
    "src/index.js~OVApi#getCards",
    "method"
  ],
  [
    "src/index.js~ovapi#getdetailedcardinfo",
    "class/src/index.js~OVApi.html#instance-method-getDetailedCardInfo",
    "src/index.js~OVApi#getDetailedCardInfo",
    "method"
  ],
  [
    "src/index.js~ovapi#gettransactions",
    "class/src/index.js~OVApi.html#instance-method-getTransactions",
    "src/index.js~OVApi#getTransactions",
    "method"
  ],
  [
    "src/index.js~ovapi#gettransactionsnrc",
    "class/src/index.js~OVApi.html#instance-method-getTransactionsNRC",
    "src/index.js~OVApi#getTransactionsNRC",
    "method"
  ],
  [
    "src/index.js~ovapi#refreshtoken",
    "class/src/index.js~OVApi.html#instance-method-refreshToken",
    "src/index.js~OVApi#refreshToken",
    "method"
  ],
  [
    "src/throw-if-missing.js",
    "file/src/throw-if-missing.js.html",
    "src/throw-if-missing.js",
    "file"
  ]
]